### PR TITLE
add nvidia Docker setup

### PR DESCRIPTION
**Pull request by MayNiklas**
# Description

Whisper heavily benefits from NVIDIA CUDA.
In my opinion, this project should support a setup in which GPU's are being used.

I added the following:
* `Dockerfile.gpu`: a separate Dockerfile for people who want to use CUDA.
* `README.md`: added the section `Using NVIDIA CUDA with docker-compose`
* `docker-compose.yml`: prepared the file for people who want to use CUDA

This effectively results in GPU support for the project.

This is just a suggestion on how I would implement CUDA support for the project!
Feel free to request changes to my PR! I'm also able to test everything in regard to CUDA.

Suggestion:
The CUDA image is based on Ubuntu.
In case you like my suggested changes, it could make sense to move `Dockerfile` to something closer to Ubuntu -> both Dockerfiles would be more similar.

# Checklist:

- [ ] My code has been linted to follow the code style of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by olekenneth** [comment]
Thanks! This is awesome. Have you tested it?

**Comment by MayNiklas** [comment]
> Thanks! This is awesome. Have you tested it?

I did test it!
I can confirm, that tasks are being successfully offloaded to the GPU with this setup.

Loading the model into the VRAM takes a few seconds. Once the model is loaded - the performance is amazing!

Only thing to consider:
The GPU being used needs to have enough VRAM for the model being used: https://github.com/openai/whisper#available-models-and-languages

-> it could make sense to limit the tasks being put onto the GPU by checking VRAM:

```python
# check if NVIDIA CUDA is being used
if torch.cuda.is_available():

  # depending on the vRAM size, we can use a different model
  vram_model_map = {
    "large": 10,
    "medium": 5,
    "small": 2,
    "base": 1,
    }

    # find the best fitting model for the available GPU memory
    for model_name, vram_size in vram_model_map.items():
      if torch.cuda.get_device_properties(0).total_memory >= vram_size * 1e9:
        print(f"model {model_name} is the biggest one available on this GPU.")
```

When the model is being loaded, the device parameter can be used to force the usage of CPU.

Maybe I should add a the warning, that users should make sure enough VRAM is available to the README?

What do you think?

**Comment by olekenneth** [comment]
This is where we expose the available options so the user can choose model:
https://github.com/schibsted/WAAS/blob/de4f6256136c8cfa8553f7ab2251d581a14d1e10/src/main.py#L99

Maybe run the script and only expose available models? Or like you say run on CPU if GPU is not an option for the selected model.

**Comment by MayNiklas** [comment]
> 
> https://github.com/schibsted/WAAS/blob/de4f6256136c8cfa8553f7ab2251d581a14d1e10/src/main.py#L99
> 

In my opinion, whisper.available_models() is not that effective:
It lists all models whisper currently supports without checking compatibility with the hardware it's running on.

For reference:
https://github.com/openai/whisper/blob/7858aa9c08d98f75575035ecd6481f462d66ca27/whisper/__init__.py#L69

Also:
It would make sense to only expect the GPU to be exposed to the worker -> decision needs to be made there.

But:
That's a separate issue that has nothing to do with supporting GPU's 🤔
With CPU transcribing the same issue exists on systems with low amount of RAM.

Do you think I should change something about my PR? Are there any changes from my side required?
I have some experiences with CUDA & different deployments; if you need my help solving a problem in that regard, just mention me!
 
In my opinion, we have two separate tasks to solve:
* add support for GPU's / documentation -> this PR
* add checks, that make sure only options compatible to the hardware are getting executed -> affects GPU & CPU transcribing

What do you think?

**Comment by olekenneth** [comment]
Sure. Merging this. Can you look into limit the models in a separate PR?

**Review by Johannes-Andersen — APPROVED** [review]

**Comment by olekenneth** [comment]
I'm getting this error:

    waas-worker-1  | /usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py:88: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:109.)
    waas-worker-1  |   return torch._C._cuda_getDeviceCount() > 0

After some research this is a problem with whisper not pulling in a torch with cuda support by default. Proof:
```
root@ca5eaaf77749:/usr/local/lib/python3.10/dist-packages/torch# cat version.py
__version__ = '1.13.1+rocm5.2'
debug = False
cuda = None
git_version = '49444c3e546bf240bed24a101e747422d1f8a0ee'
hip = '5.2.21151-afdc89f8'
```

**Comment by MayNiklas** [comment]
@olekenneth I'm running this setup for a week without any problems!

Did you install https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker ?
Have you made the changes in the docker-compose file I described in the README?

I just executed the same commands you did and came to a different result:
```sh
docker compose build --no-cache 
docker run --rm -it docker.io/library/waas-worker bash -c "cat /usr/local/lib/python3.10/dist-packages/torch/version.py"
__version__ = '1.13.1+cu117'
debug = False
cuda = '11.7'
git_version = '49444c3e546bf240bed24a101e747422d1f8a0ee'
hip = None
```

Maybe try executing a known working image?
```sh
docker run --rm --runtime=nvidia --gpus all nvidia/cuda:11.6.2-base-ubuntu20.04 nvidia-smi
```
Does your GPU get detected here?

**Comment by olekenneth** [comment]
Yes. I can run nvidia-smi inside the docker without problems. Strange.

**Comment by MayNiklas** [comment]
@olekenneth My system also has CUDA installed outside of Docker.
For reference: https://developer.nvidia.com/cuda-downloads?target_os=Linux
IIRC, the CUDA stuff depends on a Kernel module: you need to have installed CUDA outside of Docker as well!
The CUDA docker image is way way smaller compared to the CUDA dependencies in itself -> it still depends on those Kernel modules!

I'm not 100% sure about this, since my experiences with CUDA through Docker are a bit limited. For me, it just worked 😅

**Comment by MayNiklas** [comment]
> I'm getting this error:
> 
> ```
> waas-worker-1  | /usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py:88: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:109.)
> waas-worker-1  |   return torch._C._cuda_getDeviceCount() > 0
> ```
> 
> After some research this is a problem with whisper not pulling in a torch with cuda support by default. Proof:
> 
> ```
> root@ca5eaaf77749:/usr/local/lib/python3.10/dist-packages/torch# cat version.py
> __version__ = '1.13.1+rocm5.2'
> debug = False
> cuda = None
> git_version = '49444c3e546bf240bed24a101e747422d1f8a0ee'
> hip = '5.2.21151-afdc89f8'
> ```

I found the solution to your problem:
you need to make sure, that the image tag used in the Dockerfile matches the CUDA version you have installed on your system.
We should add this to the README!

**Comment by MayNiklas** [comment]
@olekenneth that also means, that using the "latest" image could make sense.

**Pull request merged**
